language: cpp

branches:
  only:
  - master

git:
  depth: 1
  
sudo: required
dist: trusty

install:
    - bash ci-scripts/$TRAVIS_OS_NAME/travis-install.sh
script:
    - bash ci-scripts/$TRAVIS_OS_NAME/travis-build.sh

matrix:
    include:
        - os: linux
          compiler: gcc
          cache: ccache
        - os: linux
          compiler: clang
        - os: osx
          osx_image: xcode8.3

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "$GITUSERNAME"
  - git config --local user.email "$GITEMAIL"
  - export TRAVIS_TAG="OTX-nightly-"$(date +'%Y-%m-%d')
  - git tag -f $TRAVIS_TAG
  - bash ci-scripts/$TRAVIS_OS_NAME/travis-buildpkg.sh
deploy:
  provider: releases
  api_key:
         secure: "GpOSmSKy5hqECYQa1Yd0EQ1T8xSeKe5FKxEcLzg7e14k7Fu4i8D+yl5ZrXZZSmjWznvGmd+vZ8UdbzL8ar+/fpw5UmT8x2BcJkOvrpSqihIdsEe1OYMfKKWTy3MYPF2g9rB2nAZXVbrCuVKySqIR9nnA9rLIEO2vk4NP8BpzSvF82vH2IY4RAkE246qgTjkUMlYKw/ngmNQzHzBVVMFXlXm8ldvZH48kSD4oesllLUcK+PAuBGIq6wsk1JzK1fpJrvHZkoxdDMLdUUGoiG07qBrZkcKeAxmjy66+Gb7ey1BVWORzH3fdy3ZxWGAGIVZZ/ACMqU69Pc9g6xvOXrdtUIsa2d6LAdHHtiAFG/4Cfwt38LQrTkZ9Cz5b1yb40roWpSqcAu1veMxolyXCHLXqHlk8xWx5uZUurOJ9S0swNgxH12ufv/nDgTRaNMsgiHJWdSIdVwZjMe32rEuf3rG5VLQTefzqYlG0JbokIsfAMHiK+Vs1ntsYGjZhZz+GrcjeumiaXuWW92vtzYOD7Q4EMMjKmmSmBFk0SwoJCyGoNZ7ZEmAoVWqVQMHO9zbXG5KXiR9SVHQJrozEaI+i0Fo9zLJ54RTQq5P+vvl5FC7yl4qQNblR44af/pkahZqv4KS6zmvNAWva8SIm1AMyvXouPDqhuUv9LScSSU6v+adOERI="
  file_glob: true
  file: toonz/build/toonz/OpenToonz-OTX-$TRAVIS_OS_NAME.*
  skip_cleanup: true
  overwrite: true
  on:
    branch: master

