language: cpp

branches:
  only:
  - OTX

git:
  depth: 1
  
sudo: required
dist: trusty

install:
    - bash ci-scripts/$TRAVIS_OS_NAME/travis-install.sh
script:
    - bash ci-scripts/$TRAVIS_OS_NAME/travis-build.sh

matrix:
    include:
        - os: linux
          compiler: gcc
          cache: ccache
        - os: linux
          compiler: clang
        - os: osx
          osx_image: xcode8.3

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "manongjohn"
  - git config --local user.email "dancel@ptd.net"
  - export TRAVIS_TAG="OTX-nightly-"$(date +'%Y-%m-%d')
  - git tag -f $TRAVIS_TAG
  - bash ci-scripts/$TRAVIS_OS_NAME/travis-buildpkg.sh
deploy:
  provider: releases
  api_key:
       secure: "$SECURETOKEN"
  file_glob: true
  file: toonz/sources/toonz/OpenToonz-OTX-$TRAVIS_OS_NAME.*
  skip_cleanup: true
  overwrite: true
  on:
    branch: OTX

