language: cpp

branches:
  only:
  - OTX

git:
  depth: 1
  
sudo: required
dist: trusty

install:
    - bash ci-scripts/$TRAVIS_OS_NAME/travis-install.sh
script:
    - bash ci-scripts/$TRAVIS_OS_NAME/travis-build.sh

matrix:
    include:
        - os: linux
          compiler: gcc
          cache: ccache
        - os: linux
          compiler: clang
        - os: osx
          osx_image: xcode8.3

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "manongjohn"
  - git config --local user.email "dancel@ptd.net"
  - export TRAVIS_TAG="OTX-nightly-"$(date +'%Y-%m-%d')
  - git tag -f $TRAVIS_TAG
  - bash ci-scripts/$TRAVIS_OS_NAME/travis-buildpkg.sh
deploy:
  provider: releases
  api_key:
  secure: "NDUhF8o4dTJwEVkrV7B46r/d+6gBdbINFThTCU0sjFVxk1DveV3wRr2Fn6UJWMKIemxg950m2Vp2fxvYbaqvs68tdvoo7BRmxuaKWmhzDXr2naFtqr0adWpoS/MX53UgNda3t9HDuTPbaoJEBBl/SlT4p2JGyP5WQhEUH2p93dOV/a1SIKwUEQo2FEgHGr/WRLbWLBJXafeAGkU8eeRDs7QJOzO56dwQYREpsq4fdSdLhbKvrq6PL9h2/Ki0wM3RtK8oueNZgMeAceoxSBeFjcreGPL9VjFWe8llFSPzgM+Bn218i9ft+KByjEINbmamqDjPcIS1ZM1Ob79Tl+jbggsdc2KZvv/xG3N85x1T0OzzzXvfDGOQ7TqvSMbDv6JTcOAIL2VCu9+Ftc/6l3U+Wd96G3XpE4sTHwUAFt0FTG5/85u3NziPXOlT6oMC3CFyhDuH4llAfS1CJvDq00m37z01MMNj/Nd1FjE3yEKY1t2XHWjl5KQ20s4hq9JDkWIdqciUDv2OMQytk+qrHcoZNkEwJ8VbzPIuLSxIEc/M2cNuKg99lTrcagfTPdp3xSi+KDat1yrAf0iZ9dwI28iL6uuUGmeiR++2zaiSb+P56AeJlnK3rqjZlJtshVV9d0qBvBL9bVL3shThaX0rRuhUdfLsyb2kiV2kuk3xWL+V994="
  file_glob: true
  file: toonz/sources/toonz/OpenToonz-OTX-$TRAVIS_OS_NAME.*
  skip_cleanup: true
  overwrite: true
  on:
    branch: OTX

